# Generated by Django 5.0 on 2024-01-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='size',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='SharedSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility_expiry', models.DateTimeField()),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.snippet')),
            ],
        ),
    ]
